<%
db_host    = ENV.fetch('DB_HOST', ENV.fetch('KRAZOWNIK_FORUM_DB_1_PORT_5432_TCP_ADDR', 'localhost'))
db_port    = ENV['KRAZOWNIK_FORUM_DB_1_PORT_5432_TCP_PORT'] || ENV['DB_PORT'] || 5432
require 'etc'
pool_size =
  # Web: max workers * max threads
  ENV.fetch('WEB_CONCURRENCY', 3).to_i * ENV.fetch('MAX_THREADS', 5).to_i +
  # ActiveJob Async max thread pool size
  Etc.nprocessors
ERB
%>

defaults: &defaults
  adapter: postgresql
  min_messages: WARNING
  pool: <%= pool_size %>
  host: <%= db_host %>
  port: <%= db_port %>
  username: <%= ENV.fetch('DB_USERNAME', 'krazownik_forum_dev').inspect %>
  password: <%= ENV.fetch('DB_PASSWORD', "krazownik_forum").inspect %>
  encoding: utf8

development:
  <<: *defaults
  database: krazownik_forum_dev

test:
  <<: *defaults
  database: krazownik_forum_test


production:
  <<: *defaults
  encoding: utf8
  min_messages: WARNING
  url: <%= ENV['DATABASE_URL'].inspect if ENV['DATABASE_URL'] %>
  database: <%= 'krazownik_forum_prod' unless ENV['DATABASE_URL'] %>
